### ISSUE TITLE
[BUG] I can't import any of the merlion subpachages

### ISSUE THREAD

**Issue by Zohoor-NezahdHalafi** [salesforce/Merlion#70] opened 2022-02-07 04:16 UTC
**Describe the bug**
I was able to import merlion. but to install and apply any of the following sub packages it was unsucceful and I am getting error 
that No module is available:
from merlion.utils.time_series import TimeSeries
from merlion.evaluate.forecast import ForecastMetric
from merlion.models.automl.autosarima import AutoSarima, AutoSarimaConfig
from merlion.models.automl.seasonality_mixin import SeasonalityLayer
from merlion.models.forecast.sarima import Sarima

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
My expectation is to be able to install these sub packages. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04 LTS]
 - Merlion Version [e.g. 1.0.0]
 - Spyder=5

**Additional context**

**Comment by aadyotb** [comment] 2022-02-10 00:33
Can you describe how you tried to install Merlion & from what directory you're attempting to make these calls? What platform are you trying to do this on?

**Comment by Zohoor-NezahdHalafi** [comment] 2022-02-10 01:42
Hi,
Thank you for your email. I am following the instructions in
salesforce-merlion. And I am able to install merlion but I get different
errors on the rest of the codes.
Also, I can't run the prophet module in merlion, it keeps sending the error
message:
ImportError: No module named 'prophet'. Try installing Merlion with
optional dependencies using `pip install salesforce-merlion[prophet]` or
`pip install `salesforce-merlion[all]`
And the other error I get is on, ModuleNotFoundError: No module named
'merlion.models.automl.seasonality_mixin'.

Your help is really appreciated.

Thank you

**Comment by garimasingh2016** [comment] 2022-03-04 19:02
I am having the same issue as the original post. It's a rather difficult issue to track down because `conda list` shows the package as installed and there's no dependency issues or anything when installing. I've tried install with pip, conda, and mamba and get the same issue.

Installation works in the base environment, but not in a conda environment.

**Comment by aadyotb** [comment] 2022-03-29 22:28
I'm unable to reproduce the error, even in conda. Closing the issue unless there are further updates with a line-by-line log of exactly how the environment was configured & how Merlion installation was conducted.

**Closed by aadyotb** 2022-03-29 22:28 UTC
